version: '3.8'

services:
  conversion-service:
    build:
      context: .
      dockerfile: Dockerfile.conversion
    container_name: conversion-service
    ports:
      - "8001:8001"

  system-service:
    build:
      context: .
      dockerfile: Dockerfile.system
    container_name: system-service
    ports:
      - "8002:8002"